[build]
  command = "streamlit run app.py"
  publish = "."

[build.environment]
  PIP_DISABLE_PIP_VERSION_CHECK = "1"
  PYTHON_VERSION = "3.11"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
